#!/usr/bin/env bash
# =============================================================================
# deploy.sh – build and deploy the code-execution MCP server + AWS sandbox
#
# Usage:
#   ./deploy.sh [--env dev|staging|prod] [--region us-east-1]
#
# Prerequisites:
#   - AWS CLI configured (aws configure / environment vars / instance profile)
#   - Terraform >= 1.6 installed
#   - Python 3.10+ with pip
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults (override with flags)
# ---------------------------------------------------------------------------
ENV="dev"
REGION="us-east-1"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)    ENV="$2";    shift 2 ;;
    --region) REGION="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$ROOT_DIR/infrastructure"

echo "==> Deploying code-execution sandbox (env=$ENV, region=$REGION)"

# ---------------------------------------------------------------------------
# 1. Install MCP server dependencies
# ---------------------------------------------------------------------------
echo ""
echo "── Step 1: Installing MCP server Python dependencies"
pip install -q -r "$ROOT_DIR/requirements.txt"
echo "   Done."

# ---------------------------------------------------------------------------
# 2. Terraform init + apply
# ---------------------------------------------------------------------------
echo ""
echo "── Step 2: Provisioning AWS infrastructure with Terraform"
cd "$INFRA_DIR"

terraform init -input=false

terraform apply \
  -auto-approve \
  -input=false \
  -var="aws_region=$REGION" \
  -var="environment=$ENV"

# ---------------------------------------------------------------------------
# 3. Export Lambda name for the MCP server
# ---------------------------------------------------------------------------
echo ""
echo "── Step 3: Reading Terraform outputs"

LAMBDA_NAME=$(terraform output -raw lambda_function_name)
INVOKE_POLICY=$(terraform output -raw mcp_invoke_policy_arn)

echo "   Lambda function : $LAMBDA_NAME"
echo "   MCP invoke policy (attach to your caller role): $INVOKE_POLICY"

# ---------------------------------------------------------------------------
# 4. Write a .env file for convenient local testing
# ---------------------------------------------------------------------------
ENV_FILE="$ROOT_DIR/.env"
cat >"$ENV_FILE" <<EOF
# Auto-generated by deploy.sh – $(date -u '+%Y-%m-%dT%H:%M:%SZ')
LAMBDA_FUNCTION_NAME=$LAMBDA_NAME
AWS_REGION=$REGION
MAX_EXECUTION_TIMEOUT=30
EOF

echo ""
echo "── Step 4: Wrote environment variables to $ENV_FILE"

# ---------------------------------------------------------------------------
# 5. Quick smoke test
# ---------------------------------------------------------------------------
echo ""
echo "── Step 5: Smoke-testing the Lambda directly"
RESULT=$(aws lambda invoke \
  --function-name "$LAMBDA_NAME" \
  --region "$REGION" \
  --payload '{"code":"print(\"hello from sandbox\")","timeout":5}' \
  --cli-binary-format raw-in-base64-out \
  /tmp/lambda_smoke_output.json \
  --query 'StatusCode' \
  --output text)

if [[ "$RESULT" == "200" ]]; then
  echo "   Status: $RESULT ✓"
  echo "   Output: $(cat /tmp/lambda_smoke_output.json)"
else
  echo "   ERROR: Lambda invocation returned HTTP $RESULT" >&2
  exit 1
fi

echo ""
echo "==> Deployment complete!"
echo ""
echo "To start the MCP server locally:"
echo "  export \$(cat .env | xargs)"
echo "  python src/server.py"
echo ""
echo "To add the MCP server to Claude Code (~/.claude/claude.json):"
echo "  {"
echo "    \"mcpServers\": {"
echo "      \"code-execution\": {"
echo "        \"command\": \"python\","
echo "        \"args\": [\"$(pwd)/src/server.py\"],"
echo "        \"env\": {"
echo "          \"LAMBDA_FUNCTION_NAME\": \"$LAMBDA_NAME\","
echo "          \"AWS_REGION\": \"$REGION\""
echo "        }"
echo "      }"
echo "    }"
echo "  }"
